version: '2'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: alexxvazquezz/nginx
    volumes:
     - ./public:/var/www/html
    ports:
     - "80:80"
    command: "service nginx start"
